services:
  spring-app:
    image: kubernetes-backend:local
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: my-db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USERNAME: root
      DB_PASSWORD: pwd1234
    depends_on:
      my-db:
        condition: service_healthy

  my-db:
    image: mysql:8.0
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppwd1234"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql-data: